#!/usr/bin/env bash
#
# Plan Forge — Project Setup Wizard (Bash)
#
# Usage:
#   ./setup.sh --preset dotnet --path ~/projects/MyApp --name MyApp
#   ./setup.sh                  # Interactive mode
#   ./setup.sh --force          # Overwrite existing files
#
# Presets: dotnet, typescript, python, java, go, azure-iac, custom

set -euo pipefail

TEMPLATE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ─── Defaults ──────────────────────────────────────────────────────────
PRESET=""
PROJECT_PATH=""
PROJECT_NAME=""
FORCE=false
AUTO_DETECT=false
AGENTS="copilot"

# ─── Color helpers ─────────────────────────────────────────────────────
cyan()   { printf '\033[0;36m%s\033[0m\n' "$*"; }
green()  { printf '\033[0;32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[0;33m%s\033[0m\n' "$*"; }
red()    { printf '\033[0;31m%s\033[0m\n' "$*"; }

# ─── Parse arguments ──────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --preset|-p)  PRESET="$2"; shift 2 ;;
        --path)       PROJECT_PATH="$2"; shift 2 ;;
        --name|-n)    PROJECT_NAME="$2"; shift 2 ;;
        --agent)      AGENTS="$2"; shift 2 ;;
        --force|-f)   FORCE=true; shift ;;
        --auto-detect|-a) AUTO_DETECT=true; shift ;;
        --help|-h)
            echo "Usage: ./setup.sh [--preset dotnet|typescript|python|java|go|azure-iac|custom] [--path DIR] [--name NAME] [--agent copilot|claude|cursor|codex|all] [--force] [--auto-detect]"
            exit 0 ;;
        *) red "Unknown option: $1"; exit 1 ;;
    esac
done

# ─── Helpers ───────────────────────────────────────────────────────────
prompt_value() {
    local message="$1"
    local default="${2:-}"
    local value
    if [[ -n "$default" ]]; then
        read -rp "$message [$default]: " value
        echo "${value:-$default}"
    else
        while true; do
            read -rp "$message: " value
            [[ -n "$value" ]] && break
        done
        echo "$value"
    fi
}

copy_with_create() {
    local src="$1"
    local dst="$2"
    local dst_dir
    dst_dir="$(dirname "$dst")"

    mkdir -p "$dst_dir"

    if [[ -f "$dst" ]] && [[ "$FORCE" != true ]]; then
        yellow "  SKIP  $dst (exists)"
        return 1
    fi

    cp "$src" "$dst"
    green "  COPY  $dst"
    return 0
}

replace_placeholders() {
    local file="$1"
    local name="$2"
    local stack="$3"
    local today
    today="$(date +%Y-%m-%d)"

    [[ ! -f "$file" ]] && return

    if [[ "$(uname)" == "Darwin" ]]; then
        sed -i '' "s|<YOUR PROJECT NAME>|${name}|g" "$file"
        sed -i '' "s|<YOUR TECH STACK>|${stack}|g" "$file"
        sed -i '' "s|<YOUR BUILD COMMAND>|${BUILD_CMD}|g" "$file"
        sed -i '' "s|<YOUR TEST COMMAND>|${TEST_CMD}|g" "$file"
        sed -i '' "s|<YOUR LINT COMMAND>|${LINT_CMD}|g" "$file"
        sed -i '' "s|<YOUR DEV COMMAND>||g" "$file"
        sed -i '' "s|<DATE>|${today}|g" "$file"
    else
        sed -i "s|<YOUR PROJECT NAME>|${name}|g" "$file"
        sed -i "s|<YOUR TECH STACK>|${stack}|g" "$file"
        sed -i "s|<YOUR BUILD COMMAND>|${BUILD_CMD}|g" "$file"
        sed -i "s|<YOUR TEST COMMAND>|${TEST_CMD}|g" "$file"
        sed -i "s|<YOUR LINT COMMAND>|${LINT_CMD}|g" "$file"
        sed -i "s|<YOUR DEV COMMAND>||g" "$file"
        sed -i "s|<DATE>|${today}|g" "$file"
    fi
}

# ─── Agent Adapter: Claude Code ────────────────────────────────────────
install_claude_agent() {
    local target="$1"
    echo "  Installing Claude Code files..."

    # Generate rich CLAUDE.md — copilot-instructions + all instruction files
    local copilot_instr="$target/.github/copilot-instructions.md"
    local claude_ctx="$target/CLAUDE.md"
    if [ -f "$copilot_instr" ] && [ ! -f "$claude_ctx" ]; then
        {
            echo "# Project Context for Claude"
            echo ""
            echo "> Auto-generated by Plan Forge. Includes project instructions + all guardrail files."
            echo "> Regenerate with: pforge smith or re-run setup with --agent claude"
            echo ""
            echo "## How to Use These Guardrails"
            echo ""
            echo "This file contains domain-specific guardrails organized by section. When editing code:"
            echo "- Editing database/SQL/repository code → follow the **database** section"
            echo "- Editing auth/JWT/OIDC code → follow the **auth** section"
            echo "- Editing API controllers/routes → follow the **api-patterns** section"
            echo "- Editing tests → follow the **testing** section"
            echo "- Editing Docker/deploy files → follow the **deploy** section"
            echo "- Always follow **architecture-principles** and **security** sections"
            echo ""
            echo "**After every file edit**: Scan for TODO, FIXME, HACK, stub, placeholder markers. Warn immediately if found."
            echo ""
            echo "**Before editing any file**: If a hardened plan exists in \`docs/plans/\`, check its Forbidden Actions section. Do not edit files listed there."
            echo ""
            echo "**Pipeline flow**: After completing a step, tell the user what to invoke next:"
            echo "- After Step 0 (Specify) → \`/planforge-step1-preflight-check\`"
            echo "- After Step 2 (Harden) → \`/planforge-step3-execute-slice\`"
            echo "- After Step 4 (Sweep) → Start a NEW session for Step 5 (Review)"
            echo "- After Step 5 (Review) → \`/planforge-step6-ship\`"
            echo ""
            echo "## Project Instructions"
            echo ""
            cat "$copilot_instr"
            echo ""

            # Embed all instruction files by domain
            local instr_dir="$target/.github/instructions"
            if [ -d "$instr_dir" ]; then
                echo "---"
                echo ""
                echo "## Guardrail Files"
                echo ""
                echo "The following guardrails are auto-loaded in VS Code Copilot by file type. In Claude, they are embedded here for reference."
                echo ""
                for instr_file in "$instr_dir"/*.instructions.md; do
                    [ -f "$instr_file" ] || continue
                    local domain
                    domain="$(basename "$instr_file" .instructions.md)"
                    echo "### $domain"
                    echo ""
                    # Strip YAML frontmatter
                    sed -n '/^---$/,/^---$/!p' "$instr_file" | tail -n +1
                    echo ""
                done
            fi
        } > "$claude_ctx"
        green "  CREATE CLAUDE.md (project context + guardrails)"
    fi

    # Convert ALL prompts → Claude skills
    local prompts_dir="$target/.github/prompts"
    local skills_dir="$target/.claude/skills"
    if [ -d "$prompts_dir" ]; then
        for prompt_file in "$prompts_dir"/*.prompt.md; do
            [ -f "$prompt_file" ] || continue
            local base
            base="$(basename "$prompt_file" .prompt.md)"
            local skill_dir="$skills_dir/planforge-$base"
            local skill_file="$skill_dir/SKILL.md"
            mkdir -p "$skill_dir"

            local desc="Plan Forge prompt"
            local got_desc
            got_desc="$(grep -oP 'description:\s*"?\K[^"]+' "$prompt_file" 2>/dev/null | head -1)" || true
            [ -n "$got_desc" ] && desc="$got_desc"

            {
                echo "---"
                echo "name: planforge-$base"
                echo "description: $desc"
                echo "metadata:"
                echo "  author: plan-forge"
                echo "  source: .github/prompts/$(basename "$prompt_file")"
                echo "user-invocable: true"
                echo "argument-hint: \"Provide context or parameters for this prompt\""
                echo "---"
                echo ""
                cat "$prompt_file"
            } > "$skill_file"
            green "  CREATE .claude/skills/planforge-$base/SKILL.md"
        done
    fi

    # Convert reviewer agents → Claude skills
    local agents_dir="$target/.github/agents"
    if [ -d "$agents_dir" ]; then
        for agent_file in "$agents_dir"/*.agent.md; do
            [ -f "$agent_file" ] || continue
            local base
            base="$(basename "$agent_file" .agent.md)"
            local skill_dir="$skills_dir/planforge-$base"
            local skill_file="$skill_dir/SKILL.md"
            mkdir -p "$skill_dir"

            local desc="Plan Forge reviewer agent"
            local got_desc
            got_desc="$(grep -oP 'description:\s*"?\K[^"]+' "$agent_file" 2>/dev/null | head -1)" || true
            [ -n "$got_desc" ] && desc="$got_desc"

            {
                echo "---"
                echo "name: planforge-$base"
                echo "description: $desc"
                echo "metadata:"
                echo "  author: plan-forge"
                echo "  source: .github/agents/$(basename "$agent_file")"
                echo "user-invocable: true"
                echo "argument-hint: \"Specify files or areas to review\""
                echo "---"
                echo ""
                cat "$agent_file"
            } > "$skill_file"
            green "  CREATE .claude/skills/planforge-$base/SKILL.md"
        done
    fi
}

# ─── Agent Adapter: Cursor ─────────────────────────────────────────────
install_cursor_agent() {
    local target="$1"
    echo "  Installing Cursor files..."

    # Generate rich .cursor/rules — copilot-instructions + all guardrails
    local copilot_instr="$target/.github/copilot-instructions.md"
    local cursor_dir="$target/.cursor"
    local cursor_rules="$cursor_dir/rules"
    if [ -f "$copilot_instr" ] && [ ! -f "$cursor_rules" ]; then
        mkdir -p "$cursor_dir"
        {
            cat "$copilot_instr"
            echo ""
            echo "---"
            echo ""
            echo "## Plan Forge Agent Guidelines"
            echo ""
            echo "When editing code, apply the guardrail section that matches the file type:"
            echo "- Database/SQL/ORM → **database** section | Auth/JWT → **auth** section"
            echo "- API routes → **api-patterns** section | Tests → **testing** section"
            echo "- Always follow **architecture-principles** and **security**"
            echo ""
            echo "After every file edit: scan for TODO/FIXME/HACK/stub markers. Warn immediately."
            echo "Before editing: check the active plan's Forbidden Actions — do not touch listed files."
            echo ""

            local instr_dir="$target/.github/instructions"
            if [ -d "$instr_dir" ]; then
                echo "---"
                echo ""
                echo "## Guardrail Files (from Plan Forge)"
                echo ""
                for instr_file in "$instr_dir"/*.instructions.md; do
                    [ -f "$instr_file" ] || continue
                    local domain
                    domain="$(basename "$instr_file" .instructions.md)"
                    echo "### $domain"
                    echo ""
                    sed -n '/^---$/,/^---$/!p' "$instr_file" | tail -n +1
                    echo ""
                done
            fi
        } > "$cursor_rules"
        green "  CREATE .cursor/rules (project context + guardrails)"
    fi

    # Convert ALL prompts → Cursor commands
    local prompts_dir="$target/.github/prompts"
    local commands_dir="$cursor_dir/commands"
    if [ -d "$prompts_dir" ]; then
        mkdir -p "$commands_dir"
        for prompt_file in "$prompts_dir"/*.prompt.md; do
            [ -f "$prompt_file" ] || continue
            local base
            base="$(basename "$prompt_file" .prompt.md)"
            local cmd_file="$commands_dir/planforge.$base.md"
            if [ ! -f "$cmd_file" ]; then
                local desc="Plan Forge prompt"
                local got_desc
                got_desc="$(grep -oP 'description:\s*"?\K[^"]+' "$prompt_file" 2>/dev/null | head -1)" || true
                [ -n "$got_desc" ] && desc="$got_desc"
                {
                    echo "---"
                    echo "description: $desc"
                    echo "---"
                    echo ""
                    cat "$prompt_file"
                } > "$cmd_file"
                green "  CREATE .cursor/commands/planforge.$base.md"
            fi
        done
    fi

    # Convert reviewer agents → Cursor commands
    local agents_dir="$target/.github/agents"
    if [ -d "$agents_dir" ]; then
        mkdir -p "$commands_dir"
        for agent_file in "$agents_dir"/*.agent.md; do
            [ -f "$agent_file" ] || continue
            local base
            base="$(basename "$agent_file" .agent.md)"
            local cmd_file="$commands_dir/planforge.$base.md"
            if [ ! -f "$cmd_file" ]; then
                local desc="Plan Forge reviewer"
                local got_desc
                got_desc="$(grep -oP 'description:\s*"?\K[^"]+' "$agent_file" 2>/dev/null | head -1)" || true
                [ -n "$got_desc" ] && desc="$got_desc"
                {
                    echo "---"
                    echo "description: $desc"
                    echo "---"
                    echo ""
                    cat "$agent_file"
                } > "$cmd_file"
                green "  CREATE .cursor/commands/planforge.$base.md"
            fi
        done
    fi
}

# ─── Agent Adapter: Codex CLI ──────────────────────────────────────────
install_codex_agent() {
    local target="$1"
    echo "  Installing Codex CLI files..."

    # Convert ALL prompts → Codex skills
    local prompts_dir="$target/.github/prompts"
    local skills_dir="$target/.agents/skills"
    if [ -d "$prompts_dir" ]; then
        for prompt_file in "$prompts_dir"/*.prompt.md; do
            [ -f "$prompt_file" ] || continue
            local base
            base="$(basename "$prompt_file" .prompt.md)"
            local skill_dir="$skills_dir/planforge-$base"
            local skill_file="$skill_dir/SKILL.md"
            mkdir -p "$skill_dir"

            local desc="Plan Forge prompt"
            local got_desc
            got_desc="$(grep -oP 'description:\s*"?\K[^"]+' "$prompt_file" 2>/dev/null | head -1)" || true
            [ -n "$got_desc" ] && desc="$got_desc"

            {
                echo "---"
                echo "name: planforge-$base"
                echo "description: $desc"
                echo "metadata:"
                echo "  author: plan-forge"
                echo "  source: .github/prompts/$(basename "$prompt_file")"
                echo "---"
                echo ""
                cat "$prompt_file"
            } > "$skill_file"
            green "  CREATE .agents/skills/planforge-$base/SKILL.md"
        done
    fi

    # Convert reviewer agents → Codex skills
    local agents_dir="$target/.github/agents"
    if [ -d "$agents_dir" ]; then
        for agent_file in "$agents_dir"/*.agent.md; do
            [ -f "$agent_file" ] || continue
            local base
            base="$(basename "$agent_file" .agent.md)"
            local skill_dir="$skills_dir/planforge-$base"
            local skill_file="$skill_dir/SKILL.md"
            mkdir -p "$skill_dir"

            local desc="Plan Forge reviewer"
            local got_desc
            got_desc="$(grep -oP 'description:\s*"?\K[^"]+' "$agent_file" 2>/dev/null | head -1)" || true
            [ -n "$got_desc" ] && desc="$got_desc"

            {
                echo "---"
                echo "name: planforge-$base"
                echo "description: $desc"
                echo "metadata:"
                echo "  author: plan-forge"
                echo "  source: .github/agents/$(basename "$agent_file")"
                echo "---"
                echo ""
                cat "$agent_file"
            } > "$skill_file"
            green "  CREATE .agents/skills/planforge-$base/SKILL.md"
        done
    fi
}

detect_preset() {
    local target="$1"

    # .NET markers
    if find "$target" -maxdepth 3 -name "*.csproj" -o -name "*.sln" -o -name "*.fsproj" 2>/dev/null | head -1 | grep -q .; then
        yellow "  AUTO-DETECT  Found .NET project markers"
        echo "dotnet"
        return
    fi

    # Go markers
    if [[ -f "$target/go.mod" ]]; then
        yellow "  AUTO-DETECT  Found Go project markers"
        echo "go"
        return
    fi

    # Java markers
    if [[ -f "$target/pom.xml" ]] || [[ -f "$target/build.gradle" ]] || [[ -f "$target/build.gradle.kts" ]]; then
        yellow "  AUTO-DETECT  Found Java project markers"
        echo "java"
        return
    fi

    # Python markers
    if [[ -f "$target/pyproject.toml" ]] || [[ -f "$target/requirements.txt" ]] || [[ -f "$target/setup.py" ]] || [[ -f "$target/Pipfile" ]]; then
        yellow "  AUTO-DETECT  Found Python project markers"
        echo "python"
        return
    fi

    # TypeScript/Node markers
    if [[ -f "$target/package.json" ]] || [[ -f "$target/tsconfig.json" ]]; then
        yellow "  AUTO-DETECT  Found TypeScript/Node project markers"
        echo "typescript"
        return
    fi

    # Azure IaC markers
    if find "$target" -maxdepth 4 -name "*.bicep" -o -name "bicepconfig.json" -o -name "azure.yaml" 2>/dev/null | head -1 | grep -q .; then
        yellow "  AUTO-DETECT  Found Azure IaC project markers"
        echo "azure-iac"
        return
    fi
    if find "$target" -maxdepth 4 -name "*.tf" 2>/dev/null | head -1 | grep -q .; then
        yellow "  AUTO-DETECT  Found Terraform project markers"
        echo "azure-iac"
        return
    fi

    yellow "  AUTO-DETECT  No known markers found — using 'custom'"
    echo "custom"
}

# ─── Banner ────────────────────────────────────────────────────────────
echo ""
cyan "╔══════════════════════════════════════════════════════════════╗"
cyan "║       Plan Forge — Project Setup Wizard              ║"
cyan "║       Bootstraps planning pipeline + tech instructions      ║"
cyan "╚══════════════════════════════════════════════════════════════╝"
echo ""

# ─── Interactive Prompts ───────────────────────────────────────────────
if [[ -z "$PROJECT_PATH" ]]; then
    PROJECT_PATH="$(prompt_value "Target project directory" "$(pwd)")"
fi

# Resolve to absolute path
PROJECT_PATH="$(cd "$PROJECT_PATH" 2>/dev/null && pwd || echo "$PROJECT_PATH")"

if [[ ! -d "$PROJECT_PATH" ]]; then
    yellow "Creating directory: $PROJECT_PATH"
    mkdir -p "$PROJECT_PATH"
fi

if [[ -z "$PROJECT_NAME" ]]; then
    default_name="$(basename "$PROJECT_PATH")"
    PROJECT_NAME="$(prompt_value "Project name" "$default_name")"
fi

if [[ -z "$PRESET" ]]; then
    if [[ "$AUTO_DETECT" == true ]]; then
        echo ""
        cyan "Auto-detecting tech stack..."
        PRESET="$(detect_preset "$PROJECT_PATH")"
        if [[ "$FORCE" != true ]]; then
            read -rp "Detected preset: $PRESET. Is this correct? (Y/n) " confirm_preset
            if [[ -n "$confirm_preset" ]] && [[ "$confirm_preset" != [yY]* ]]; then
                echo ""
                cyan "Available presets:"
                echo "  1) dotnet      — .NET / C# / ASP.NET Core"
                echo "  2) typescript  — TypeScript / React / Node.js / Express"
                echo "  3) python      — Python / FastAPI / SQLAlchemy"
                echo "  4) java        — Java / Spring Boot / Gradle / Maven"
                echo "  5) go          — Go / Chi / Gin / Standard Library"
                echo "  6) azure-iac   — Azure Bicep / Terraform / PowerShell / azd"
                echo "  7) custom      — Shared files only (add your own instructions)"
                echo ""
                choice="$(prompt_value "Select preset (1-7 or name)" "1")"
                case "$choice" in
                    1|dotnet)     PRESET="dotnet" ;;
                    2|typescript) PRESET="typescript" ;;
                    3|python)     PRESET="python" ;;
                    4|java)       PRESET="java" ;;
                    5|go)         PRESET="go" ;;
                    6|azure-iac)  PRESET="azure-iac" ;;
                    7|custom)     PRESET="custom" ;;
                    *)            PRESET="$choice" ;;
                esac
            fi
        fi
    else
        echo ""
        cyan "Available presets:"
        echo "  1) dotnet      — .NET / C# / ASP.NET Core"
        echo "  2) typescript  — TypeScript / React / Node.js / Express"
        echo "  3) python      — Python / FastAPI / SQLAlchemy"
        echo "  4) java        — Java / Spring Boot / Gradle / Maven"
        echo "  5) go          — Go / Chi / Gin / Standard Library"
        echo "  6) azure-iac   — Azure Bicep / Terraform / PowerShell / azd"
        echo "  7) custom      — Shared files only (add your own instructions)"
        echo ""
        choice="$(prompt_value "Select preset (1-7 or name)" "1")"
        case "$choice" in
            1|dotnet)     PRESET="dotnet" ;;
            2|typescript) PRESET="typescript" ;;
            3|python)     PRESET="python" ;;
            4|java)       PRESET="java" ;;
            5|go)         PRESET="go" ;;
            6|azure-iac)  PRESET="azure-iac" ;;
            7|custom)     PRESET="custom" ;;
            *)            PRESET="$choice" ;;
        esac
    fi
fi

case "$PRESET" in
    dotnet)     STACK_LABEL=".NET / C# / ASP.NET Core" ;;
    typescript) STACK_LABEL="TypeScript / React / Node.js" ;;
    python)     STACK_LABEL="Python / FastAPI" ;;
    java)       STACK_LABEL="Java / Spring Boot" ;;
    go)         STACK_LABEL="Go / Standard Library" ;;
    azure-iac)  STACK_LABEL="Azure Bicep / Terraform / PowerShell / azd" ;;
    custom)     STACK_LABEL="Custom (configure manually)" ;;
    *)          red "Unknown preset: $PRESET"; exit 1 ;;
esac

# ─── Build/Test/Lint Commands ──────────────────────────────────────────
# Normalise: split comma-separated preset string into array
IFS=',' read -ra PRESETS <<< "$PRESET"
for i in "${!PRESETS[@]}"; do
    PRESETS[$i]="$(echo "${PRESETS[$i]}" | tr -d ' ')"
done

VALID_PRESETS=(dotnet typescript python java go azure-iac custom)
for p in "${PRESETS[@]}"; do
    valid=false
    for v in "${VALID_PRESETS[@]}"; do [[ "$p" == "$v" ]] && valid=true && break; done
    if [[ "$valid" != true ]]; then
        red "  ERROR  Unknown preset '$p'. Valid values: ${VALID_PRESETS[*]}"
        exit 1
    fi
done

# Determine if custom-only
IS_CUSTOM_ONLY=false
if [[ "${#PRESETS[@]}" -eq 1 ]] && [[ "${PRESETS[0]}" == "custom" ]]; then
    IS_CUSTOM_ONLY=true
fi

# Primary preset drives build/test/lint defaults
PRIMARY_PRESET="custom"
for p in "${PRESETS[@]}"; do
    if [[ "$p" != "custom" ]]; then PRIMARY_PRESET="$p"; break; fi
done

case "$PRIMARY_PRESET" in
    dotnet)     DEFAULT_BUILD="dotnet build"; DEFAULT_TEST="dotnet test"; DEFAULT_LINT="dotnet format --verify-no-changes" ;;
    typescript) DEFAULT_BUILD="pnpm build"; DEFAULT_TEST="pnpm test"; DEFAULT_LINT="pnpm lint" ;;
    python)     DEFAULT_BUILD="python -m build"; DEFAULT_TEST="pytest"; DEFAULT_LINT="ruff check ." ;;
    java)       DEFAULT_BUILD="./gradlew build"; DEFAULT_TEST="./gradlew test"; DEFAULT_LINT="./gradlew spotlessCheck" ;;
    go)         DEFAULT_BUILD="go build ./..."; DEFAULT_TEST="go test ./..."; DEFAULT_LINT="golangci-lint run" ;;
    azure-iac)  DEFAULT_BUILD="az bicep build --file infra/main.bicep"; DEFAULT_TEST="Invoke-Pester -Path ./tests -Output Detailed"; DEFAULT_LINT="az bicep lint --file infra/main.bicep" ;;
    custom)     DEFAULT_BUILD=""; DEFAULT_TEST=""; DEFAULT_LINT="" ;;
esac

if [[ "$FORCE" != true ]]; then
    echo ""
    cyan "Build/Test/Lint commands (press Enter for defaults):"
    BUILD_CMD="$(prompt_value "Build command" "$DEFAULT_BUILD")"
    TEST_CMD="$(prompt_value "Test command" "$DEFAULT_TEST")"
    LINT_CMD="$(prompt_value "Lint command" "$DEFAULT_LINT")"
else
    BUILD_CMD="$DEFAULT_BUILD"
    TEST_CMD="$DEFAULT_TEST"
    LINT_CMD="$DEFAULT_LINT"
fi

# ─── Summary ───────────────────────────────────────────────────────────
echo ""
cyan "Configuration:"
echo "  Project:  $PROJECT_NAME"
echo "  Path:     $PROJECT_PATH"
echo "  Preset(s): ${PRESETS[*]} ($STACK_LABEL)"
echo "  Build:    $BUILD_CMD"
echo "  Test:     $TEST_CMD"
echo "  Lint:     $LINT_CMD"
echo "  Force:    $FORCE"
echo ""

if [[ "$FORCE" != true ]]; then
    read -rp "Proceed? (Y/n) " confirm
    if [[ -n "$confirm" ]] && [[ "$confirm" != [yY]* ]]; then
        red "Aborted."
        exit 0
    fi
fi

# ─── Step 1: Copy Core Files ──────────────────────────────────────────
echo ""
cyan "Step 1: Core planning files"

declare -A CORE_FILES=(
    ["docs/plans/AI-Plan-Hardening-Runbook.md"]="docs/plans/AI-Plan-Hardening-Runbook.md"
    ["docs/plans/AI-Plan-Hardening-Runbook-Instructions.md"]="docs/plans/AI-Plan-Hardening-Runbook-Instructions.md"
    ["docs/plans/README.md"]="docs/plans/README.md"
    ["docs/plans/DEPLOYMENT-ROADMAP-TEMPLATE.md"]="docs/plans/DEPLOYMENT-ROADMAP.md"
    ["docs/plans/PROJECT-PRINCIPLES-TEMPLATE.md"]="docs/plans/PROJECT-PRINCIPLES-TEMPLATE.md"
)

for src_rel in "${!CORE_FILES[@]}"; do
    dst_rel="${CORE_FILES[$src_rel]}"
    src="$TEMPLATE_ROOT/$src_rel"
    dst="$PROJECT_PATH/$dst_rel"
    if [[ -f "$src" ]]; then
        copy_with_create "$src" "$dst" || true
    else
        yellow "  WARN  Source not found: $src_rel"
    fi
done

# ─── Step 2: Copy Shared Instruction Files ─────────────────────────────
echo ""
cyan "Step 2: Shared instruction files"

SHARED_FILES=(
    ".github/instructions/ai-plan-hardening-runbook.instructions.md"
    ".github/instructions/architecture-principles.instructions.md"
    ".github/instructions/git-workflow.instructions.md"
    "templates/.github/instructions/project-principles.instructions.md:.github/instructions/project-principles.instructions.md"
)

for rel in "${SHARED_FILES[@]}"; do
    if [[ "$rel" == *":"* ]]; then
        src="$TEMPLATE_ROOT/${rel%%:*}"
        dst="$PROJECT_PATH/${rel##*:}"
    else
        src="$TEMPLATE_ROOT/$rel"
        dst="$PROJECT_PATH/$rel"
    fi
    if [[ -f "$src" ]]; then
        copy_with_create "$src" "$dst" || true
    fi
done

# ─── Step 3: Copy Preset Files ────────────────────────────────────────
if [[ "$IS_CUSTOM_ONLY" != true ]]; then
    is_first_preset=true

    for active_preset in "${PRESETS[@]}"; do
        [[ "$active_preset" == "custom" ]] && continue

        echo ""
        cyan "Step 3: $active_preset preset files"

        PRESET_DIR="$TEMPLATE_ROOT/presets/$active_preset"
        if [[ ! -d "$PRESET_DIR" ]]; then
            red "  ERROR  Preset directory not found: $PRESET_DIR"
            exit 1
        fi

        # Copy all files from preset, preserving relative paths
        while IFS= read -r -d '' file; do
            rel_path="${file#"$PRESET_DIR/"}"
            dst="$PROJECT_PATH/$rel_path"
            copy_with_create "$file" "$dst" || true
        done < <(find "$PRESET_DIR" -type f -print0)

        # First preset sets copilot-instructions.md; subsequent ones don't overwrite
        preset_copilot="$PRESET_DIR/.github/copilot-instructions.md"
        root_copilot="$PROJECT_PATH/.github/copilot-instructions.md"
        if [[ "$is_first_preset" == true ]] && [[ -f "$preset_copilot" ]] && [[ ! -f "$root_copilot" ]]; then
            copy_with_create "$preset_copilot" "$root_copilot" || true
        fi

        # First preset sets AGENTS.md; subsequent ones don't overwrite
        preset_agents="$PRESET_DIR/AGENTS.md"
        root_agents="$PROJECT_PATH/AGENTS.md"
        if [[ "$is_first_preset" == true ]] && [[ -f "$preset_agents" ]] && [[ ! -f "$root_agents" ]]; then
            copy_with_create "$preset_agents" "$root_agents" || true
        fi

        is_first_preset=false
    done
else
    echo ""
    cyan "Step 3: Custom preset — copying template copilot-instructions.md only"

    src="$TEMPLATE_ROOT/.github/copilot-instructions.md"
    dst="$PROJECT_PATH/.github/copilot-instructions.md"
    if [[ -f "$src" ]]; then
        copy_with_create "$src" "$dst" || true
    fi
fi

# ─── Step 3b: Copy Shared Agents ───────────────────────────────────────
if [[ "$IS_CUSTOM_ONLY" != true ]]; then
    echo ""
    cyan "Step 3b: Shared agents (cross-stack reviewers + pipeline agents)"

    # Shared agents (api-contract, accessibility, multi-tenancy, cicd, observability, dependency, compliance)
    SHARED_AGENTS_DIR="$TEMPLATE_ROOT/presets/shared/.github/agents"
    if [[ -d "$SHARED_AGENTS_DIR" ]]; then
        while IFS= read -r -d '' file; do
            filename="$(basename "$file")"
            dst="$PROJECT_PATH/.github/agents/$filename"
            copy_with_create "$file" "$dst" || true
        done < <(find "$SHARED_AGENTS_DIR" -name "*.agent.md" -type f -print0)
    fi

    # Pipeline agents (specifier, plan-hardener, executor, reviewer-gate, shipper)
    PIPELINE_AGENTS_DIR="$TEMPLATE_ROOT/templates/.github/agents"
    if [[ -d "$PIPELINE_AGENTS_DIR" ]]; then
        while IFS= read -r -d '' file; do
            filename="$(basename "$file")"
            dst="$PROJECT_PATH/.github/agents/$filename"
            copy_with_create "$file" "$dst" || true
        done < <(find "$PIPELINE_AGENTS_DIR" -name "*.agent.md" -type f -print0)
    fi
fi

# ─── Step 3c: Copy Project Principles Prompt + Extension Templates ─────
if [[ "$IS_CUSTOM_ONLY" != true ]]; then
    echo ""
    cyan "Step 3c: Project Principles prompt + extension templates + hooks"

    # Project Principles prompt
    pp_prompt_src="$TEMPLATE_ROOT/templates/.github/prompts/project-principles.prompt.md"
    pp_prompt_dst="$PROJECT_PATH/.github/prompts/project-principles.prompt.md"
    if [[ -f "$pp_prompt_src" ]]; then
        copy_with_create "$pp_prompt_src" "$pp_prompt_dst" || true
    fi

    # Extension template directory
    ext_template_src="$TEMPLATE_ROOT/templates/.forge"
    if [[ -d "$ext_template_src" ]]; then
        while IFS= read -r -d '' file; do
            rel_path="${file#"$ext_template_src/"}"
            dst="$PROJECT_PATH/.forge/$rel_path"
            copy_with_create "$file" "$dst" || true
        done < <(find "$ext_template_src" -type f -print0)
    fi

    # Hooks
    hooks_src="$TEMPLATE_ROOT/templates/.github/hooks"
    if [[ -d "$hooks_src" ]]; then
        while IFS= read -r -d '' file; do
            rel_path="${file#"$hooks_src/"}"
            dst="$PROJECT_PATH/.github/hooks/$rel_path"
            copy_with_create "$file" "$dst" || true
        done < <(find "$hooks_src" -type f -print0)
    fi
fi

# ─── Step 4: Replace Placeholders ─────────────────────────────────────
echo ""
cyan "Step 4: Replacing placeholders"

while IFS= read -r -d '' file; do
    replace_placeholders "$file" "$PROJECT_NAME" "$STACK_LABEL"
done < <(find "$PROJECT_PATH" -name "*.md" -type f -print0)

green "  DONE  Placeholders replaced"

# ─── Step 5: Generate .forge.json ─────────────────────────────
echo ""
cyan "Step 5: Generating .forge.json"

CONFIG_PATH="$PROJECT_PATH/.forge.json"
VERSION_FILE="$TEMPLATE_ROOT/VERSION"
TEMPLATE_VERSION="1.0.0"
if [[ -f "$VERSION_FILE" ]]; then
    TEMPLATE_VERSION="$(tr -d '\n' < "$VERSION_FILE")"
fi
cat > "$CONFIG_PATH" <<EOF
{
  "projectName": "$PROJECT_NAME",
  "preset": "$(IFS=','; echo "${PRESETS[*]}")",
  "agents": "$AGENTS",
  "stack": "$STACK_LABEL",
  "setupDate": "$(date +%Y-%m-%d)",
  "templateVersion": "$TEMPLATE_VERSION"
}
EOF

green "  CREATED  .forge.json"

# ─── Step 5b: Generate capabilities.json (machine-readable discovery) ────
CAPABILITIES_PATH="$PROJECT_PATH/.forge/capabilities.json"
mkdir -p "$(dirname "$CAPABILITIES_PATH")"

PROMPT_LIST="[]"
if [[ -d "$PROJECT_PATH/.github/prompts" ]]; then
    PROMPT_LIST=$(find "$PROJECT_PATH/.github/prompts" -maxdepth 1 -name "*.prompt.md" -printf '"%f",' 2>/dev/null | sed 's/,$//' | awk '{print "["$0"]"}')
    [[ "$PROMPT_LIST" == "[]" ]] || true
fi

AGENT_LIST="[]"
if [[ -d "$PROJECT_PATH/.github/agents" ]]; then
    AGENT_LIST=$(find "$PROJECT_PATH/.github/agents" -maxdepth 1 -name "*.agent.md" -printf '"%f",' 2>/dev/null | sed 's/,$//' | awk '{print "["$0"]"}')
    [[ "$AGENT_LIST" == "[]" ]] || true
fi

SKILL_LIST="[]"
if [[ -d "$PROJECT_PATH/.github/skills" ]]; then
    SKILL_LIST=$(find "$PROJECT_PATH/.github/skills" -mindepth 1 -maxdepth 1 -type d -printf '"%f",' 2>/dev/null | sed 's/,$//' | awk '{print "["$0"]"}')
    [[ "$SKILL_LIST" == "[]" ]] || true
fi

INSTR_LIST="[]"
if [[ -d "$PROJECT_PATH/.github/instructions" ]]; then
    INSTR_LIST=$(find "$PROJECT_PATH/.github/instructions" -maxdepth 1 -name "*.instructions.md" -printf '"%f",' 2>/dev/null | sed 's/,$//' | awk '{print "["$0"]"}')
    [[ "$INSTR_LIST" == "[]" ]] || true
fi

cat > "$CAPABILITIES_PATH" <<EOF
{
  "generatedBy": "plan-forge-setup",
  "generatedAt": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "preset": "$(IFS=','; echo "${PRESETS[*]}")",
  "prompts": ${PROMPT_LIST:-[]},
  "skills": ${SKILL_LIST:-[]},
  "instructions": ${INSTR_LIST:-[]},
  "hooks": [".github/hooks/plan-forge.json"]
}
EOF

green "  CREATED  .forge/capabilities.json"

# ─── Step 6: Copy VS Code Settings Template ────────────────────────────
echo ""
cyan "Step 6: VS Code settings template"

vscode_src="$TEMPLATE_ROOT/templates/vscode-settings.json.template"
vscode_dst="$PROJECT_PATH/.vscode/settings.json"
if [[ -f "$vscode_src" ]]; then
    copy_with_create "$vscode_src" "$vscode_dst" || true
fi

# ─── Step 6b: Install Agent Adapters ───────────────────────────────────
AGENT_LIST="$AGENTS"
if [[ "$AGENT_LIST" == "all" ]]; then
    AGENT_LIST="copilot,claude,cursor,codex"
fi

IFS=',' read -ra AGENT_ARRAY <<< "$AGENT_LIST"
EXTRA_AGENTS=()
for ag in "${AGENT_ARRAY[@]}"; do
    ag="$(echo "$ag" | tr -d ' ')"
    [[ "$ag" != "copilot" ]] && EXTRA_AGENTS+=("$ag")
done

if [[ ${#EXTRA_AGENTS[@]} -gt 0 ]]; then
    echo ""
    cyan "Step 6b: Agent adapters (${EXTRA_AGENTS[*]})"

    for ag in "${EXTRA_AGENTS[@]}"; do
        case "$ag" in
            claude) install_claude_agent "$PROJECT_PATH" ;;
            cursor) install_cursor_agent "$PROJECT_PATH" ;;
            codex)  install_codex_agent "$PROJECT_PATH" ;;
            *) yellow "  Unknown agent: $ag — skipping" ;;
        esac
    done
fi

# ─── Step 7: Copy Copilot VS Code Guide ────────────────────────────────
guide_src="$TEMPLATE_ROOT/docs/COPILOT-VSCODE-GUIDE.md"
guide_dst="$PROJECT_PATH/docs/COPILOT-VSCODE-GUIDE.md"
if [[ -f "$guide_src" ]]; then
    copy_with_create "$guide_src" "$guide_dst" || true
fi

# ─── Done ──────────────────────────────────────────────────────────────
echo ""
green "╔══════════════════════════════════════════════════════════════╗"
green "║                    Setup Complete!                          ║"
green "╚══════════════════════════════════════════════════════════════╝"
echo ""
cyan "Files installed to: $PROJECT_PATH"
echo ""
yellow "Next steps:"
echo "  1. Review .github/copilot-instructions.md — fill in project-specific details"
echo "  2. Review AGENTS.md — customize worker patterns for your app"
echo "  3. Review .vscode/settings.json — uncomment instruction file references"
echo "  4. Review .github/prompts/ — customize scaffolding recipes for your conventions"
echo "  5. Review .github/agents/ — tailor reviewer checklists for your project"
echo "  6. Review .github/skills/ — update build/deploy commands for your CI/CD"
echo "  7. Review docs/plans/DEPLOYMENT-ROADMAP.md — add your phases"
echo "  8. Read docs/COPILOT-VSCODE-GUIDE.md for Copilot Agent Mode workflow"
echo "  9. Start planning: open docs/plans/AI-Plan-Hardening-Runbook-Instructions.md"
echo ""
yellow "Optional (recommended):"
echo "  - Run .github/prompts/project-profile.prompt.md to generate project-specific guardrails"
echo "  - Run .github/prompts/project-principles.prompt.md to define project principles"
echo "  - Use .github/prompts/step0-specify-feature.prompt.md to define your first feature"
echo ""

# ─── Step 8: Auto-validate ─────────────────────────────────────────────
cyan "Running validation..."
validate_script="$TEMPLATE_ROOT/validate-setup.sh"
if [[ -f "$validate_script" ]]; then
    bash "$validate_script" --path "$PROJECT_PATH"
fi
