/**
 * The Plan Forge agent plugin (plugins/plan-forge) and its marketplace entry.
 * Generated by scripts/build-agent-plugin.mjs from canonical sources; these
 * tests hold it to the Agent Plugins 1.0 layout and keep it from going stale.
 */

import { describe, it, expect } from "vitest";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join, resolve } from "node:path";
import {
  buildPluginFiles, checkPlugin, PLUGIN_DIR, MARKETPLACE_FILE, PLUGIN_NAME,
} from "../../scripts/build-agent-plugin.mjs";

const ROOT = resolve(import.meta.dirname, "..", "..");
const files = buildPluginFiles({ root: ROOT });
const read = (rel) => JSON.parse(files.get(rel));

describe("agent plugin manifest", () => {
  const manifest = read(`${PLUGIN_DIR}/plugin.json`);

  // From https://agent-plugins.org/schemas/1.0.0/plugin.schema.json (additionalProperties: false).
  const ALLOWED_FIELDS = ["$schema", "name", "version", "description", "author", "homepage", "repository", "license", "keywords", "extensions"];
  const NAME_PATTERN = /^(?!.*(?:--|\.\.))[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?$/;

  it("declares Agent Plugins 1.0 with only schema fields and a valid name", () => {
    expect(manifest.$schema).toBe("https://agent-plugins.org/schemas/1.0.0/plugin.schema.json");
    expect(Object.keys(manifest).filter((key) => !ALLOWED_FIELDS.includes(key))).toEqual([]);
    expect(Object.keys(manifest.author).filter((key) => !["name", "email", "url"].includes(key))).toEqual([]);
    expect(manifest.name).toMatch(NAME_PATTERN);
    expect(manifest.license).toBe("MIT");
  });

  it("is listed by the repository's marketplace", () => {
    const market = read(MARKETPLACE_FILE);
    expect(market.plugins).toEqual([expect.objectContaining({ name: PLUGIN_NAME, source: PLUGIN_DIR })]);
  });
});

describe("agent plugin contents", () => {
  const paths = [...files.keys()];

  it("ships every shared skill", () => {
    const skills = readdirSync(join(ROOT, "presets/shared/skills"));
    for (const skill of skills) expect(paths).toContain(`${PLUGIN_DIR}/skills/${skill}/SKILL.md`);
  });

  it("ships the pipeline agents under the Copilot namespace", () => {
    const agents = readdirSync(join(ROOT, "templates/.github/agents"));
    for (const agent of agents) expect(paths).toContain(`${PLUGIN_DIR}/com.github.copilot/agents/${agent}`);
  });

  it("ships the automation templates unchanged", () => {
    const dir = join(ROOT, "templates/.github/automations");
    for (const name of readdirSync(dir)) {
      expect(files.get(`${PLUGIN_DIR}/automations/${name}`)).toBe(readFileSync(join(dir, name), "utf8").replace(/\r\n/g, "\n"));
    }
  });

  it("leaves no per-project setup placeholder unresolved", () => {
    const withPlaceholders = paths.filter((p) => /<YOUR [A-Z ]+>/.test(files.get(p)));
    expect(withPlaceholders).toEqual([]);
  });

  it("contains no MCP server or hooks (both stay project-installed)", () => {
    expect(paths.some((p) => /\/(mcp|\.mcp)\.json$/.test(p))).toBe(false);
    expect(paths.some((p) => p.includes("/hooks/"))).toBe(false);
  });
});

describe.skipIf(!existsSync(join(ROOT, PLUGIN_DIR)))("committed agent plugin", () => {
  it("matches its sources (run node scripts/build-agent-plugin.mjs)", () => {
    expect(checkPlugin({ root: ROOT })).toEqual({ stale: [], missing: [], extra: [] });
  });
});
